version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
      - run:
          name: Run hadolint
          command: hadolint Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push image
          command: |
            chmod +x build_push_image_karsajobs_ui.sh
            ./build_push_image_karsajobs_ui.sh

workflows:
  version: 2
  lint-and-build-karsajobs-ui:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile