version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
      - run:
          name: Run hadolint
          command: hadolint Dockerfile

  test-app:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push image
          command: |
            chmod +x build_push_image_karsajobs.sh
            ./build_push_image_karsajobs.sh

workflows:
  version: 2
  lint-test-and-build-karsajobs:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app